### ISSUE TITLE
schema spec should include standard method of schema version determination

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/single-cell-curation#142]
Recommend that we document a standard method to determine, from an H5AD or CXG:
* is the dataset conforming to a Corpora schema?
* And if so, which version?

In addition, we need to formalize which versions _must_ be supported by our code for backward compat.

There are varied "version sniffing" algos implemented (eg, in single-cell-explorer backend), which are needed to multiplex old Corpora specs (eg, to extract various metadata).

**Comment by maniarathi** [comment]
This is part of the way there, no? https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#uns-dataset-metadata

**Comment by bkmartinjr** [comment]
how so?  It is completely different than earlier versions, so at a minimum we need to define precedence...

(which isn't hard - I'd just rather we were intentional and explicit, so each SW module doesn't do something different)

**Comment by brianraymor** [comment]
See my comments in [**wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1632155652158300?thread_ts=1631558116.107400&cid=C024HCSH9PT). Both 2.0.0 and 1.1.0 define a mechanism for introspecting the version. For 1.1.0 - https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/1.1.0/corpora_schema.md#schema-version. For 2.0.0 - see Arathi's comment above. 

It sounds like you want to define a software "policy" that uses these mechanisms, but that should not be in the schema specification. 

Further, the `cellxgene-schema` was a complete rewrite and does not support 1.1.0. Following re-curation, the portal will remove all references to legacy schemas.  

I'm probably missing some subtlety here because it's Monday and Day 0 for me after vacation ;-)

**Comment by brianraymor** [comment]
Closed per conversation with @bkmartinjr ... and conclusion of wrangling thread.
