### ISSUE TITLE
cellxgene-schema must warn when a Seurat conversion cannot be performed

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#162]
#### Context

See conversations on [**ux**](https://czi-sci.slack.com/archives/C02450L5YAX/p1635211104016200) and [**ingestion**](https://czi-sci.slack.com/archives/C02JP4SALNQ/p1635184609017000). 

Also - [Seurat Failure Investigations](https://docs.google.com/document/d/1AHN3Jkz3mb3T1F-Tr3h3cTrKotE6Ls2SPHg3wB5ppiI/edit#heading=h.ukkfc1tjv8r1). 

---
#### Design

**Note**: _Updated to reflect the comment thread below._

When present, both raw and final matrices must be examined - `adata.X` and `adata.raw.X`. See [matrix layers](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#x-matrix-layers) for background. 

If the matrix includes more than 2^32-1 non-zero elements, it exceeds the constraints of the R (dgCMatrix). Subsequent seurat conversion on the portal will fail. 

The `cellxgene-schema` CLI MUST display this warning:

_This dataset cannot be converted to the .rds (Seurat v3) format. **fill-in-the-blank** nonzero elements in **fill-in-the-blank-matrix-name** exceed the limitations in the R dgCMatrix sparse matrix class (2147483647  nonzero elements)._

and then continue processing

**Comment by danieljhegeman** [comment]
> Just to clarify, this should be done for both the raw and the final matrices.

So do this check for adata.X and adata.raw.X (if available)

**Comment by danieljhegeman** [comment]
Just to be precise here, the following message does _not_ accurately state the possible reasons for failing seurat convertibility due to size limitations:

> This dataset cannot be converted to the .rds (Seurat v3) format. fill-in-the-blank nonzero elements in fill-in-the-blank-matrix-name exceed the limitations in the R dgCMatrix sparse matrix class (2147483647 nonzero elements).

This is only true for sparse matrices. For dense matrices, failure will occur if any of the dimensions exceed 2 ^ 31 - 1 _irrespective of whether those elements are nonzero_.

**Comment by metakuni** [comment]
Added dependency since this change to `cellxgene-schema` needs to be released to PyPI before the corresponding change to Portal in:
* https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1579

(otherwise the Portal unit tests in CI will fail)

**Comment by metakuni** [comment]
Deployed to prod yesterday.
