### ISSUE TITLE
Add donor id field to obs

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#164]
The schema does not currently record biosample_id (also known as donor_id). Should we add support for this concept in the schema?

### Rationale

A blood dataset is submitted. That dataset comprises blood contributed by Ambrose and Jason. 

_**Story: A Data consumer would like to select blood cells that came from Jason.**_ 

_**Stor 2: A data consumer who finds two populations of T cells would like to know: Are those T cells present in both donors, or are either population specific to Ambrose or Jason?**_

**Comment by jahilton** [comment]
>biosample_id (also known as donor_id)

I think these could be determined to be separate concepts. A left eye and a right eye from Ambrose would be 1 donor_id but 2 biosample_ids.
I believe each is valuable. The Stories above illustrate the importance of donor_id.

**Story: A Data Consumer would like to compare blood cells that came from Jason at timepoint A vs timepoint B.**

**Comment by jahilton** [comment]
The need for both sample & donor identifier fields was strongly supported during a recent data integration workshop. The participants began with datasets that met schema 2.0.0. One of the first tasks that the integrators initiated was trying to identify the columns in each dataset that defined the subject & sample IDs. (The other first task was to mark each dataset as single-cell vs single-nucleus...I will create a ticket for that)

I asked a clarifying question on the definition of 'sample'. For multiplexed datasets, would you consider the 'pool' to be the 'sample' (i.e. library batch), or would you consider each biological entity that went into a pool to be a 'sample'?
The response: That is a good question and I would choose the latter and say each biological entity (draw of blood, piece of tissue etc.) is a sample, but there is something to say for the former too.

The 'pool' is likely valuable in determining 'batch'.

**Comment by jahilton** [comment]
Complications will arise in ensuring uniqueness of values (if I see DonorA in one dataset and DonorA in another dataset, do they represent the same donor?).
We _could_ append the dataset/collection ID but this will then make it difficult to actually denote the cases when the 2 DonorAs in different Collections are from the same donor.

**Comment by brianraymor** [comment]
Focus this issue on donor id. Sample id requires a proposal for review. @jahilton @BAevermann assigned.

Donor id (required string type) is unique per dataset and may be unique within a collection (strongly recommended).

**Comment by jahilton** [comment]
for a "sample" identifier, several use cases to consider when deciding what entity we want to capture here, and how to communicate that in the schema...

**1. The 1-to-1-to-1 case**
Each donor in the study provides a single specimen and each specimen is processed individually.
Very common.
No question about what entity is captured as they will all be assigned the same.

**2. The pooling/multiplexing case**
Several specimens are pooled and the pool is processed together. Various methods can be used to demultiplex the data downstream (identify a cell back to its specimen)
The guidance above from data integrators was that they want the _specimen_, not the _pool_. We also know that, in these cases, the pool is commonly noted anyway (`Processing_Cohort` [here](https://cellxgene.cziscience.com/e/218acb0f-9f2f-4f76-b90b-15a4b7c7f629.cxg/), `pool` [here](https://cellxgene.cziscience.com/e/01ad3cd7-3929-4654-84c0-6db05bd5fd59.cxg/), `pool_number` [here](https://cellxgene.cziscience.com/e/3faad104-2ab8-4434-816d-474d8d2641db.cxg/) ), and we can suggest that the pool information can be submitted separately.

**3. The longitudinal study case**
Each donor in the study may provide multiple specimens over months/years.
[This Seed Network project](https://chanzuckerberg.com/science/programs-resources/single-cell-biology/seednetworks/human-immune-variation-across-genetic-backgrounds-gender-and-time/) and [this Pediatric Network project](https://chanzuckerberg.com/science/programs-resources/single-cell-biology/pediatric-networks/a-cell-atlas-of-trained-immunity-in-bacillus-calmette-guerin-vaccinated-african-infants/) are such examples.
The entity to be captured would be the individual specimen taken at a given time point.

**4. The split tissue case**
A donor provides a single specimen and that specimen is split and each sub-specimen is processed individually. This may be for replication or for different modalities (one sub-specimen is used for expression and one for chromatic accessibility).
In [this dataset](https://cellxgene.cziscience.com/e/c6413315-7158-46c5-a5fd-7228385694f1.cxg/), coloring by `tissue` and then observing the `donor_uuid` values, you can see 3 donors have cells of 3 sub-tissues of the fallopian tube. The entity not depicted here is the fallopian tube (specimen) that each sub-specimen came from. Could be more significant distinction if a donor provides 2 specimens of the same type (eg a right & left eye) and then those are split.
In [the 2 datasets here](https://cellxgene.cziscience.com/collections/9b02383a-9358-4f0f-9795-a891ec523bcc), the `sample_uuid` values are the same because the identifiers are representing the pre-split specimen.
Unclear which entity should be captured in the proposed sample_id.

Combinations of the above cases may occur (eg longitudinal samples may be multiplexed, specimens may be pooled then split for processing)

**Comment by brianraymor** [comment]
I moved @jahilton's use cases for biosample id to a new issue and deleted his comment in this issue - [https://github.com/chanzuckerberg/single-cell-curation/issues/244](https://github.com/chanzuckerberg/single-cell-curation/issues/244). 

The question is whether we can add `donor_id` in 3.0 and consider `biosample_id` as a later increment or refinement.

**Comment by jahilton** [comment]
>The question is whether we can add donor_id in 3.0 and consider biosample_id as a later increment or refinement.

My answer would be 'yes'

**Comment by brianraymor** [comment]
@jahilton - please feel free to edit in place:

### donor_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>donor_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. If unavailable, this MUST be <code>"unknown"</code>.<br><br>
This MUST be free-text that identifies a unique biosample donor in the dataset. It is also STRONGLY RECOMMENDED that this identifier be unique within the collection of datasets that includes this dataset. 
        </td>
    </tr>
</tbody></table>
<br>

**Comment by jahilton** [comment]
### donor_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>donor_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. If unavailable, this MUST be <code>"unknown"</code>.<br><br>
This MUST be free-text that identifies a unique individual that data were derived from. It is STRONGLY RECOMMENDED that this identifier be unique to a given individual within the collection of datasets that includes this dataset. It is STRONGLY RECOMMENDED that this identifier be designed so that it is unique to a given individual across all collections. For example, rather than <code>donor1</code>, we would suggest a value that is more likely to be globally unique (e.g.  <code>SOURCE_donor1</code>, where <code>SOURCE</code> denotes the source of the biomaterial or the lab that processed the data).
        </td>
    </tr>
</tbody></table>
<br>

**Comment by brianraymor** [comment]
HuBMAP has their [own scheme](https://software.docs.hubmapconsortium.org/donor):

_This is the HuBMAP ID of the donor (e.g. HBM579.RPKF.738)_

Do any submitters offer any "guarantees" or documentation for their donor ID(s)?

**Comment by jahilton** [comment]
>Do any submitters offer any "guarantees" or documentation for their donor ID(s)?

Few will, most won't

**Comment by brianraymor** [comment]
From a side conversation with @ambrosejcarr:

> If pursuing it, I'd be interested in discussing use cases for globally unique donor IDs. I'm not able to think of anything common and compelling that's not covered by within-collection unique IDs.
>
>For example, batch effect correction and dataset integration can get by with over-segmented data.
i.e. if a true "patient" is artificially broken into 4 separate subsets, the integration algorithm will learn parameters for each subset. It may result in slight overfitting, but nothing catastrophic.

**Comment by brianraymor** [comment]
I see no way to validate uniqueness without submitters adopting a global standard. For example, for other use cases there is  [GRID](https://wmda.info/professionals/optimising-search-match-connect/why-global-identifier/).

**Comment by brianraymor** [comment]
@jahilton - I accepted editorial changes from your proposal in #267 - but not the additional recommendation _be designed so that it is unique to a given individual across all collections._

**Comment by brianraymor** [comment]
The validator could make some simple tests for uniqueness **within** a dataset. For example, ensure that other donor observations are consistent such as `sex` or `ethnicity`.

**Comment by brianraymor** [comment]
Imaging the possible heuristics that still do not catch that donor1 could also be donor2 in the same dataset or another dataset. It's just free-text unless the submitter has donor id standards.

**Dataset validation**

1. Does donor1 already exist in the set of donor labels in the portal for *other collections* ? Pick another name. It could be like finding a new google account name. Taken. Try again. Taken. Try again. Jason had some STRONGLY RECOMMENDED text for this - but it cannot be enforced. I try to avoid too many SHOULD(s) because it becomes empty blustering after a point. 
2. Does donor1 have different observations in the same dataset such as `sex`? The validator probably can't count on `development stage` because donor1 may have contributed over time? (Or would that make them donor2?)

**Collection validation**

1. Does donor1 have different observations in other datasets in the collection such as `sex`?

**Comment by jahilton** [comment]
I don't understand the downside to the additional suggestion that donor id values "be designed so that it is unique to a given individual across all collections."
I encourage these "consider data reuse" nudges wherever possible, and I do think it will result in fewer "donor1" values.

Is it that I don't mind empty blustering, and perhaps I even enjoy it?

@brianraymor you are correct that development_stage may be legitimately different for a given donor, even within the same dataset.

**Comment by pablo-gar** [comment]
> I don't understand the downside to the additional suggestion that donor id values "be designed so that it is unique to a given individual across all collections."

If they are indeed the same individual then having the same id is +++ If they are different individuals with the same ID it's actually a ---.

Downstream there can be solutions for either scenario, but for systematic solution to exist we need be clear whether we can guarantee portal-wide unique IDs per individual

**Comment by jahilton** [comment]
>If they are indeed the same individual then having the same id is +++ If they are different individuals with the same ID it's actually a ---.

I think we're saying the same thing, but we could emphasize that it should also be consistent for a given individual across all collections.

I don't see any way to guarantee portal-wide unique IDs per individual

**Comment by brianraymor** [comment]
> I don't understand the downside to the additional suggestion that donor id values "be designed so that it is unique to a given individual across all collections."

I dislike SHOULD variations because:

1. They cannot be enforced.
2. They're then ignored because `1`. The text becomes "noise" for readers of the schema to gloss over.

And in this case,  _be designed so that it is unique to a given individual across all collections_ is  an "exercise left up to the reader" despite the serving suggestion. 

How much time would Lattice invest in ensuring that submitters were nudged?

**Comment by jahilton** [comment]
We would definitely include that in our curation checks and tag it in our 'first response' as something that we'd like to update before publishing the dataset.

We are well-positioned to offer data sharing best practices. I don't think we should hesitate to do so because those best practices can't be validated.
