### ISSUE TITLE
more explicitly state that schema calls for most specific ontology term available

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#191]
In the [Integration Metadata](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#integration-metadata) section of the schema, we note

> When no appropriate ontology value is available, then the most accurate term MUST be used.

But we don't actually state anything about when an appropriate ontology term _is_ available.
In practice, and when communicating guidelines to other curators, we select the most specific term available. We can make that more clear in the schema.

**Comment by brianraymor** [comment]
@jahilton - there was agreement that editors would consistently use the most **accurate term** or **accurate child** as a preferred style rather than **specific** or **precise**. 

How about:

The most accurate ontology term MUST always be used. This is true even in cases where there may not be an appropriate ontology term ... _followed by example_

**Comment by jahilton** [comment]
That's good

**Comment by brianraymor** [comment]
Addressed in https://github.com/chanzuckerberg/single-cell-curation/pull/242/commits/f834ddfe7e3d382303992b921e3920272e4db3fb
