### ISSUE TITLE
Deprecate X_normalization

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#200]
The current curation process for X_normalization is difficult - there is no controlled vocabulary/standards defined, and the complex processes that can be done to normalize data are difficult to standardize.
We should start with revisiting the value prop. of capturing this information.

**Comment by brianraymor** [comment]
Previous conversations

1. https://czi-sci.slack.com/archives/C02TSE92DBM/p1643912712606399
2. https://czi-sci.slack.com/archives/C024HCSH9PT/p1638206303118400?thread_ts=1636591173.085000&cid=C024HCSH9PT

**Comment by BAevermann** [comment]
This becomes potentially fraught in the context of multi-omic representation where X_norm could apply to component A or component B (say RNA-seq or atac-seq).

**Comment by jychien** [comment]
Here is a first attempt at a proposal for matrix "normalization" fields:
- **value_scale**: factor by which the expression values have been transformed (none/linear, log, log1p, log base e, log base 10, log base 2, log1p base e, log1p base 10, log1p base 2)
- **normalization_method**: transformation method used to make expression values comparable across cells (none, sctransform, lognormalize, tf-idf, cpm, tpm, fpkm, rpkm, dsp, clr, maxquant, other)
- **centered**: whether the expression of genes has been shifted such that the mean or median expression across cells is 0 (boolean)
- **scaled**: whether the expression of genes across cells have been standardized such that they have the same variance or range (boolean)

optional:
- **background_substraction**: the software method used to remove ambient RNA contamination ('soupx', 'decontx', 'none')

**Comment by brianraymor** [comment]
Triaged. Proposed that we deprecate `X_normalization` and focus on a new design as part of the X matrix annotations /  Transformations design for SOMA based on clear use cases for cellxgene.

**Comment by LuckyMD** [comment]
Hey!
I just found this issue... hope it's okay if I add my 2 cents:

In a recent integration workshop based on cxg datasets, the normalization description was one of the difficulties that my team faced when deciding how to integrate the data. I think the term `lognormalize` is a bit difficult to interpret, as it could mean log1p transformation after using a specific normalization method (CPM, scran, etc.), or it could mean that raw counts were log-transformed. The former is very common but is not clear enough about the normalization method that was used. A way to make this clearer is to ask for size_factors that were used for normalization. These could just be added to the dictionary proposed by @pablo-gar and would omit the need to list all possible normalization methods that use a global size factor scaling approach.

On another note: how do we deal with vital information being stored in `.uns`, which would probably be lost in concatenation of SOMA objects, which is however needed for atlassing efforts.

**Comment by jahilton** [comment]
@LuckyMD definitely appreciate your thoughts, glad you found this issue!

The proposal is to just drop the requirement for `uns.X_normalization`, while the submission of a form of normalized data will remain STRONGLY RECOMMENDED (and submission of raw data will remain required).

For the integration use case, in which cases/datasets did you need to understand the normalization of the data instead of just using the raw counts?

**Comment by LuckyMD** [comment]
There are two things we wanted the normalized data for: (1) manually checking the data, and (2) benchmarking/testing some integration methods.

Regarding point (1): It is useful to use the pre-normalized data that the data generators used as it usually best reflects their annotations. this can then be helpful to identify outliers both in embeddings and in feature plots.

Regarding point (2): Most integration methods (Seurat, Scanorama, harmony, fastMNN, etc.) require normalized data to be input to the algorithm. If you have a lot of datasets, joint normalization across all datasets can be prohibitive (unless you just use log CPM). We worked on testing a parallelized version of scran to get around this, but this is not standard yet. Thus, it can be useful to use the already normalized data as a first step to test integration methods.

I reckon some form of normalized data is needed to visualize data in cellxgene explorer. Otherwise you can only look at count data, which is misleading. Also, things like DE tests in cellxgene (I believe t-tests from rank_genes_groups) expect (log-) normalized data as well as they are asymptotically normally distributed. So if data generators submit a data object without normalized data, maybe it's worth just running sth like log CPM before ingesting to provide at least some normalized layer?

**Comment by brianraymor** [comment]
Closed by #248
