### ISSUE TITLE
Amend "Macaca”  to "Macaca mulatta” in dataset 6acb6637-ac08-4a65-b2d1-581e51dc7ccf

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#201]
In the dataset below, some cells are from the organism "Macaca mulatta" (NCBITaxon:9544) but they were annotated as "Macaca" (NCBITaxon:9539)

Collection id: 367d95c0-0eb0-4dae-8276-9407239421ee
Collection name: Evolution of cellular diversity in primary motor cortex of human, marmoset monkey, and mouse
Dataset id: 6acb6637-ac08-4a65-b2d1-581e51dc7ccf
Dataset name: Evolution of cellular diversity in primary motor cortex of human, marmoset monkey, and mouse 4-species integration excitory neurons

**Comment by jahilton** [comment]
Revision is up

**Comment by jychien** [comment]
"Macaca" (NCBITaxon:9539) to "Macaca mulatta" (NCBITaxon:9544) for the above listed dataset looks good. 

Additional issues that we see for all of the datasets in the collection:
- Fields that are being displayed as continuous, where in actuality they should be categorical:
  - cluster_id, subclass_id, seurat_clusters.new
- Is it possible to follow up on the significance of having cluster_id, seurat_clusters.new, and seurat_clusters? It could be valid to have all three, but would be good to confirm.
- cluster_colors is in obs rather than in uns
- sample_id looks like it is cell barcodes, and has 1 cell per id, should check redundancy with index

**Comment by jahilton** [comment]
Published the revision.
Made a ticket in our JIRA to do a general review of the various things noted above for all datasets
