### ISSUE TITLE
Document process for contributors to request new ontology terms when no exact or appropriate term is available

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#235]
On a call this morning w/ @BAevermann, David OS & Bradley Varner (w/ CL), and Wei & Rachel (DCP wranglers), we discussed how cellxgene & CL can collaborate more closely. One such way was to more directly feed CL w/ New Term Requests from the contributors.

Bradley is going to make a CL Github Issue template tailored specifically for cellxgene-originated requests, in part so they can prioritize those accordingly.
We can link to that template via the cellxgene schema - I propose that we provide more guidance for `When no appropriate ontology value is available,...` in the [Integration Metadata section](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#integration-metadata).
New Term Requests for the other fields/ontologies can be directed to Lattice. A long-term goal could be the work with EFO to set up such a template for assay requests as those are by far the most common. Aside from CL & EFO, we've only had 1 NTR (in MONDO) so those rare cases can also come through us.

**Comment by brianraymor** [comment]
> Bradley is going to make a CL Github Issue template tailored specifically for cellxgene-originated requests, in part so they can prioritize those accordingly.

@jahilton - Is that template available to link? 

> New Term Requests for the other fields/ontologies can be directed to Lattice

How can these be directed to Lattice - through the cellxgene mailing list or ... ?

**Comment by jahilton** [comment]
Haven't heard back from CL. I imagine we'll touch base at next week's HCA meeting.

Yes - we should use the cellxgene mailing list for consistency.

**Comment by brianraymor** [comment]
The HCA Wrangler documentation includes information on [requesting ontology terms](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/request_ontology_terms.html). Is there any potential reuse of the information? 

Otherwise, @jahilton - comments?

For example if `cell_type_ontology_term_id` describes a relay interneuron, but the most accurate available term in the CL ontology is [CL:0000099](https://www.ebi.ac.uk/ols/ontologies/cl/terms?obo_id=CL:0000099) for *interneuron*, then the interneuron term can be used to fulfill this requirement and ensures that users searching for "neuron" are able to find these data. If no appropriate high-level term can be found or the cell type is unknown, then the most accurate term is [CL:0000003](https://www.ebi.ac.uk/ols/ontologies/cl/terms?obo_id=CL:0000003) for *native cell*.

To request new terms to be added to an ontology from the [**Required Ontologies**](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#required-ontologies), data submitters may contact our curation team at [cellxgene@chanzuckerberg.com](cellxgene@chanzuckerberg.com).

**Comment by jahilton** [comment]
I don't see a potential for reuse. That looks like guidance for how the _wranglers_ should request terms as opposed to guidance for the contributors.

I don't know enough about relay interneurons to know if it's an appropriate example, or if it would be one where we would suggest they go to CL with.
And I'll want to ask David/Bradley to see if they have any brief guidance for when new CL terms _should_ be requested.
But I would suggest...

The most accurate ontology term MUST always be used. If an exact or approximate ontology term is not available, a new term may be requested.

- For CL: data submitters may complete the term request template with CL. To meet cellxgene requirements, the most accurate available term in CL can be used. During the submission process, data submitters should notify the curators of the pending term request so that the datasets can be updated once the term is available.
- For any other ontology: data submitters may request these through the curators during the submission process.

**Comment by brianraymor** [comment]
I think that all the ontologies can have a new term requested through their issue tracker per my comments about OLS above. Why is CL treated as a special case?

**Comment by brianraymor** [comment]
Ambrose, Jason, and I have been discussing updating the schema/validator on a regular six month cadence. This issue is specific to the schema and not curation processes.

**Comment by jahilton** [comment]
>Why is CL treated as a special case?

In general, we would prefer it if we had the bandwidth to handle the NTRs for all of the ontologies. But the CL NTRs are certainly going to require the most effort - we anticipate more of them than any other ontology and they require the most biological background.
Also with the rise of single-cell data, the CL team is putting a lot of effort into connecting directly with researchers. This connection will pay off for existing terms, in addition to new ones.

Assays, for example, would not be ideal to send researchers to the ontology as we have seen some inconsistencies with how the terms are captured. So we'd be reviewing/updating those eventually anyway.

**Comment by brianraymor** [comment]
@jahilton 

I found the _Add term (cellxgene) - New term suggestion for CL via cellxgene. - template._ It's linked below. Comments?

---

The most accurate ontology term MUST always be used. If an exact or approximate ontology term is not available, a new term may be requested:

- For the [Cell Ontology], data submitters may [suggest a new term](https://github.com/obophenotype/cell-ontology/issues/new?assignees=bvarner-ebi&labels=new+term+request%2C+cellxgene&template=a_adding_term_cellxgene.md&title=%5BNTR-cxg%5D). To meet cellxgene schema requirements, the most accurate available CL term MUST be used until the new term is available. During the submission process, data submitters should [notify the curators of the pending term request](mailto:cellxgene@chanzuckerberg.com). so that the datasets can be updated once the term is available.
- For all other ontologies, data submitters may [request these through the curators](mailto:cellxgene@chanzuckerberg.com) during the submission process.

[Cell Ontology]: http://obofoundry.org/ontology/cl.html
