### ISSUE TITLE
Update feature_biotype to be annotated by the portal and not the curator

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#236]
`feature_biotype` is submitted by the curator to raw.var and .var in [schema 2.0.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#feature_biotype)
However, the value of this is consistent based on the corresponding value in the index (the validator does this check anyway), and thus, could be filled in by the portal similar to `feature_name` & `feature_reference`. As of now, everything in `gene_ercc.csv.gz` will be `spike-in` and everything in the other 3 gene files will be `gene`.
Moving this to a value automated by the portal will remove 1 more ask of curators/contributors.

**Comment by brianraymor** [comment]
I recall that we discussed having the portal apply based on the heuristic when the field was introduced, but I cannot find the  conversation. @pablo-gar - do you recall why we closed on curator applied?

**Comment by pablo-gar** [comment]
I recall this was brought up _after_ the validator for schema 2.0.0 was released. As I remember we thought this was a good idea to implement.

**Comment by brianraymor** [comment]
First pass in #256.

@jahilton @pablo-gar -

There's some additional complexity because the [index](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#index-of-pandasdataframe) is currently dependent on the value of the `feature_biotype`. The original intent was _belt and suspenders_:

If the <code>feature_biotype</code> is <code>"gene"</code> then this MUST be an ENSEMBL term. If the <code>feature_biotype</code> is <code>"spike-in"</code> then this MUST be an ERCC Spike-In identifier.

but the `feature_biotype` will not be applied until submission.

This could be rewritten to eliminate the reference to `feature_biotype`:

If the feature is a gene then this MUST be an ENSEMBL term. If the feature is a "spike-in"</code> then this MUST be an ERCC Spike-In identifier.

**Comment by jahilton** [comment]
>If the feature is a gene then this MUST be an ENSEMBL term. If the feature is a "spike-in" then this MUST be an ERCC Spike-In identifier.

This makes sense to me. May want to extend with a sample
...MUST be an ERCC Spike-In identifier (e.g. ERCC-0003).
Haven't seen anything like ERCC_0003 or ERCC0003 but wouldn't surprise me

**Comment by brianraymor** [comment]
Editorial changes addressed in https://github.com/chanzuckerberg/single-cell-curation/pull/272.
