### ISSUE TITLE
cellxgene-schema must validate donor_id

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#261]
See [schema reference](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#donor_id).

Curators MUST annotate the following column in the `obs` dataframe:

### donor_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>donor_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be free-text that identifies a unique individual that data were derived from. It is STRONGLY RECOMMENDED that this identifier be designed so that it is unique to:<br><br>
          <ul><li>a given individual within the collection of datasets that includes this dataset</li>
          <li>a given individual across all collections in the cellxgene Data Portal</li></ul>
        </td>
    </tr>
</tbody></table>

**Comment by jychien** [comment]
Since this is a free text field, it is a little bit more difficult to define stringent checking by the validator. I've focused on not allowing accidental null values getting through.
| Test Case                                                   | Expected Result | Obtained Result                                                                                                     | Test File                     | Needs attention |
| ----------------------------------------------------------- | --------------- | ------------------------------------------------------------------------------------------------------------------- | ----------------------------- | --------------- |
| scRNA-seq dataset with donor\_id column missing             | Fail validation | Failed validation                                                                                                   | adata\_no\_donor.h5ad         |                 |
| scRNA-seq dataset with donor\_id that are integers          | Fail validation | Failed validation<br>Current logging: ERROR: Column 'donor\_id' in dataframe 'obs' must be categorical, not int64.  | adata\_donor\_int.h5ad        |                 |
| scRNA-seq dataset with donor\_id that are objects           | Fail validation | Failed validation<br>Current logging: ERROR: Column 'donor\_id' in dataframe 'obs' must be categorical, not object. | adata\_donor\_object.h5ad     |                 |
| scRNA-seq dataset with empty string for subset of donor\_id | Fail validation | Passed validation                                                                                                   | adata\_donor\_empty\_str.h5ad | X               |
| scRNA-seq dataset with NaN for subset of donor\_id          | Fail validation | Passed validation                                                                                                   | adata\_donor\_nan.h5ad        | X               |

**Comment by jychien** [comment]
Looks good to me! Thanks! I'll close the ticket.
| Test Case                                                   | Expected Result | Obtained Result                                                                                           | Test File                              | Needs attention |
| ----------------------------------------------------------- | --------------- | --------------------------------------------------------------------------------------------------------- | -------------------------------------- | --------------- |
| scRNA-seq dataset with empty string for subset of donor\_id | Fail validation | Failed validation<br>Logging: ERROR: Column 'donor\_id' in dataframe 'obs' must not contain empty values. | adata\_donor\_empty\_str\_updated.h5ad |                 |
| scRNA-seq dataset with NaN for subset of donor\_id          | Fail validation | Failed validation<br>Logging: ERROR: Column 'donor\_id' in dataframe 'obs' must not contain NaN values.   | adata\_donor\_nan\_updated.h5ad        |
