### ISSUE TITLE
enrichment strategies [Jackson Labs]

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#3]
@ambrosejcarr

_I spoke with Bill Flynn this morning who is a staff scientist running the Single Cell Biology Facility at Jackson Labs, which generates ~15-30 libraries each week. He’s trying to stand up publication pages for datasets that they generate as a service to their researchers_

_Metadata schema made sense to him, thought there were two missing fields: `enrichment strategies`, (i.e. “cd45+ cells only”) and `dissociation`. **I think we can safely ignore `dissociation`**, but `enrichment strategies` is a good one for us to think about more ..._

**Comment by ambrosejcarr** [comment]
I asked @jahilton whether UBERON might be sufficient to capture cell type enrichment strategies. He said that was not likely to be generally successful, since it would require merging UBERON & CL. Here's Lattice's strategy: 

_[Lattice] captures this type of protocol in 2 separate fields
enriched_cell_types - the target population
enrichment_factors - typically protein targets used to isolate the population_

**Comment by ambrosejcarr** [comment]
We haven't heard additional requests for this feature.
