### ISSUE TITLE
2 dimensional spatial representation of MERFISH data

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#31]
It has come to our attention that there's a need from cellxgene users to visualize cells using embeddings that encode the x,y,z coordinates available in MERFISH and alike data.

A solution to this issue seems to live in the curation process rather than adding a new feature to cellxgene. An example of what could be done:

- Select a method that embeds x,y,z coordinates into two axes.
- Add an extra embedding to `AnnData.obsm`, this can then visualized in cellxgene
- [Optional] Make this process available in `cellxgene-schema apply`

What we need to figure out:

- Is this something that we want to support or should we delegate to users the creation of these embeddings?
- If we want to support it, there needs to be a discussion about how we want to approach it.

**Comment by ambrosejcarr** [comment]
> Select a method that embeds x,y,z coordinates into two axes.

I don't believe we will be able to produce a good experience for true volumetric data where the dimensions of `x ~ y ~ z`. We would simply be able to see the cells on the edges of the cube. To visualize dense volumetric data, a true 3d data viewer such as [neuroglancer](https://neuroglancerhub.github.io/) would be required. If however, the data are thin section, where the dimensions of `x ~ y >> z`, then flattening the `z` axis can produce a good experience aside from some minimal visual crowding.

We have an example spatial dataset that is formatted for use in cellxgene available [here](https://drive.google.com/file/d/1lW9tKR0jZ6uofksp0SUrQd0ywd2pNrOk/view?usp=sharing). that follows the above guidance.

> Is this something that we want to support or should we delegate to users the creation of these embeddings?

My perspective is that spatial assays are highly variable, even "MERFISH" data are formatted differently by different labs. We will rarely have sufficient context to encode a spatial embedding and so can't "support" creating it in the same way that we do with `cellxgene prepare`. We should specify in a sub-tutorial what authors should do if they have `(x, y, [z])` information. The short answer is: drop `z`, (equivalent to projecting it onto a plane) and add a `(n_cells, 2)` embedding `.obsm`. If the data come from multiple replicates, then the `x, y` information should be offset to produce a spatial grid so that the data don't improperly overlap, see e.g. the tSNE projection from the [Lung Cell Atlas](https://cellxgene.cziscience.com/e/krasnow_lab_human_lung_cell_atlas_10x-1-remixed.cxg/)

The exception to this is 10x visium. I don't think we've seen enough of this data to warrant building support into `cellxgene-schema apply`, but we should have at least a worked example we can point to that users could follow to. Perhaps Max's work on the [Simmonds](https://www.cell.com/cell/pdf/S0092-8674(20)31686-X.pdf) dataset would suffice.

**Comment by brianraymor** [comment]
No response from @pablo-gar. Closing.
