### ISSUE TITLE
unscramble skin data

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#388]
Someone informed us that the plots for marker genes in the Dataset in [c353707f-09a4-4f12-92a0-cb741e57e5f0](https://cellxgene.cziscience.com/collections/c353707f-09a4-4f12-92a0-cb741e57e5f0) are not aligning with their expected cell types.
For example, LYZ should be concentrated in the macrophage population, but it is scattered
<img width="729" alt="Screen Shot 2022-11-30 at 2 27 57 PM" src="https://user-images.githubusercontent.com/15098808/204921857-b6980b71-f0e4-440b-a849-51c1ebc7e210.png">

I confirmed this in the download h5ad using several marker genes noted in the associated publication. Both raw.X and .X data layers appear to be scrambled.
The embeddings+cell_type annotations appear to be aligned correctly.

@rachadele is investigating

**Comment by rachadele** [comment]
[X_umap.pdf](https://github.com/chanzuckerberg/single-cell-curation/files/10134566/X_umap.pdf)
I asked Jenny to help me convert directly from the contributor's Seurat object to h5ad; LYZ looks correct in this one so I assume I made a mistake during the conversion /gene mapping process. I'll look into it further :)

**Comment by rachadele** [comment]
@jychien helped me fix this issue:
<img width="1114" alt="Screen Shot 2022-12-02 at 12 40 39 PM" src="https://user-images.githubusercontent.com/51383714/205383129-0c51dfc6-9838-43de-abc2-85249d9e6692.png">

<img width="1092" alt="Screen Shot 2022-12-02 at 12 40 29 PM" src="https://user-images.githubusercontent.com/51383714/205382306-dc1d6e93-1d6a-42de-b695-4a3b5a99235b.png">

it looks like the order of .obs initially got scrambled during conversion from .rds -> anndata:
<img width="954" alt="Screen Shot 2022-12-02 at 12 44 32 PM" src="https://user-images.githubusercontent.com/51383714/205382879-1d904ef0-2e67-488f-8375-efc7be7fcb28.png">
<img width="1005" alt="Screen Shot 2022-12-02 at 12 43 54 PM" src="https://user-images.githubusercontent.com/51383714/205382898-fcc7689a-44c8-43eb-b1a9-abd5f139aa0a.png">

I will work on updating the fixed version of the h5ad  :-)

**Comment by rachadele** [comment]
https://cellxgene.cziscience.com/collections/0caff2f3-d41b-4d32-a0f9-f46b9aad248f

this is the updated revision; I believe the marker gene issue is fixed:
<img width="1243" alt="Screen Shot 2022-12-07 at 3 55 38 PM" src="https://user-images.githubusercontent.com/51383714/206323020-d9b8da0f-b0be-4f59-8756-4f643b6c8f68.png">

I also added back in the cluster numbers from the source .rds since they're a little different than the paper's cell type annotations (Here are some screenshots for context). 

<img width="283" alt="Screen Shot 2022-12-07 at 2 35 00 PM" src="https://user-images.githubusercontent.com/51383714/206323059-789e0f0f-5a64-40d2-b6fc-ffc0ed255001.png">
<img width="813" alt="Screen Shot 2022-12-07 at 2 33 40 PM" src="https://user-images.githubusercontent.com/51383714/206323245-ef38e8d9-413d-4175-9fc9-31a4c2fbc1ce.png">
<img width="410" alt="Screen Shot 2022-12-07 at 2 44 19 PM" src="https://user-images.githubusercontent.com/51383714/206323264-86798364-dc12-48f8-914b-275708431b10.png">

Can I publish/close this issue? @jahilton

**Comment by jahilton** [comment]
Looks good. @rachadele please publish the revision

**Comment by rachadele** [comment]
done!
