### ISSUE TITLE
cellxgene-schema must annotate observation_joinid

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#523]
# Design

See [schema 4](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#observation_joinid).

The current Census implementation is a base85 (rfc 1924) hash digest of the original AnnData index, implemented in chanzuckerberg/cellxgene-census#666.

# Prototype

Updated prototype based on chanzuckerberg/cellxgene-census#666.

@bkmartinjr writes:

Prototype which adds `observation_joinid` to an H5AD and writes out a new H5AD containing the modification. 

```
import os.path
import sys

import anndata
import numpy as np
from xxhash import xxh3_64_intdigest
from base64 import b85encode

"""
Annotate an H5AD with `observation_joinid`

Uses xxhash (https://xxhash.com/), via https://pypi.python.org/pypi/xxhash/.

NOTE: xxhash is licensed BSD-2
"""


def main():
    h5ad_filename = sys.argv[1]
    ad = anndata.read_h5ad(h5ad_filename)

     ad.obs["observation_joinid"] = (
            ad.obs.index.to_series()
            .map(xxh3_64_intdigest)
            .astype(np.uint64)
            .apply(lambda v: b85encode(v.to_bytes(8, "big")).decode("ascii"))
        )

    fpath, fext = os.path.splitext(h5ad_filename)
    save_to_filename = f"{fpath}_with_joinid.h5ad"
    ad.write(save_to_filename)


if __name__ == "__main__":
    sys.exit(main())
```

**Comment by bkmartinjr** [comment]
One caveat: there are open questions regarding the use of an int64 digest as applies to R users.  There is some chance we may need to move to either an int32 digest, or a string encoded 64 bit digest.  CC: @mlin @pablo-gar

**Comment by nayib-jose-gloria** [comment]
@pablo-gar this ticket is ready for QA. If you run the following command:
```
pip install git+https://github.com/chanzuckerberg/single-cell-curation/@main#subdirectory=cellxgene_schema_cli --upgrade
```

You will install a version of the CLI that outputs a labeled h5ad with an added observation_joinid column in 'obs' when you run 
`cellxgene-schema validate <input_h5ad_filepath> -a <output_labeled_h5ad_filepath>`

Let me know if you need any more info to validate that this is working as expected for the census use-case. Thanks!

**Comment by nayib-jose-gloria** [comment]
@pablo-gar Addendum to the above:

The input h5ad must pass validation to have labels (including observation_joinid) added. Because we've done some work on schema 4.0.0 validation in main, the input h5ad must follow schema 4.0.0 rules. See [here](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/tests/fixtures/h5ads/example_valid.h5ad) for an example dataset that passes 4.0.0 validation. Let me know if you need more examples. 

Changes to requirements between 3.X.X and 4.0.0 are summarized [here](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#appendix-a-changelog), let me know if you need further assistance.
