### ISSUE TITLE
cellxgene-schema CLI must download and process pinned ontologies and upgrade GENCODE versions

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#739]
### Details

The following pinned ontologies MUST be refreshed:

| Ontology | OBO Prefix | Release | Download |
|:--|:--|:--|:--|
| [Cell Ontology] | CL |  [2024-01-04] | [cl.owl]|
| [Experimental Factor Ontology] | EFO | [2024-01-15 EFO 3.62.0] | [efo.owl]
| [Mondo Disease Ontology] | MONDO | [2024-01-03] | [mondo.owl] |
| [Uberon multi-species anatomy ontology] |  UBERON | [2024-01-18] | [uberon.owl] |
| | | | |

[Cell Ontology]: http://obofoundry.org/ontology/cl.html
[2024-01-04]: https://github.com/obophenotype/cell-ontology/releases/tag/v2024-01-04
[cl.owl]: https://github.com/obophenotype/cell-ontology/releases/download/v2024-01-04/cl.owl

[Experimental Factor Ontology]: http://www.ebi.ac.uk/efo
[2024-01-15 EFO 3.62.0]: https://github.com/EBISPOT/efo/releases/tag/v3.62.0
[efo.owl]: https://github.com/EBISPOT/efo/releases/download/v3.62.0/efo.owl

[Human Ancestry Ontology]: http://www.obofoundry.org/ontology/hancestro.html
[3.0]: https://github.com/EBISPOT/hancestro/releases/tag/3.0
[hancestro-base.owl]: https://github.com/EBISPOT/hancestro/blob/3.0/hancestro-base.owl

[Human Developmental Stages]: http://obofoundry.org/ontology/hsapdv.html
[hsapdv.owl]: http://purl.obolibrary.org/obo/hsapdv.owl

[Mondo Disease Ontology]: http://obofoundry.org/ontology/mondo.html
[2024-01-03]: https://github.com/monarch-initiative/mondo/releases/tag/v2024-01-03
[mondo.owl]: https://github.com/monarch-initiative/mondo/releases/download/v2024-01-03/mondo.owl

[Mouse Developmental Stages]: http://obofoundry.org/ontology/mmusdv.html
[mmusdv.owl]: http://purl.obolibrary.org/obo/mmusdv.owl

[NCBI organismal classification]: http://obofoundry.org/ontology/ncbitaxon.html
[2023-06-20]: https://github.com/obophenotype/ncbitaxon/releases/tag/v2023-06-20
[ncbitaxon.owl]: https://github.com/obophenotype/ncbitaxon/releases/download/v2023-06-20/ncbitaxon.owl.gz

[Phenotype And Trait Ontology]: http://www.obofoundry.org/ontology/pato.html
[2023-05-18]: https://github.com/pato-ontology/pato/releases/tag/v2023-05-18
[pato.owl]: https://github.com/pato-ontology/pato/blob/v2023-05-18/pato.owl

[Uberon multi-species anatomy ontology]: http://www.obofoundry.org/ontology/uberon.html
[2024-01-18]: https://github.com/obophenotype/uberon/releases/tag/v2024-01-18
[uberon.owl]: https://github.com/obophenotype/uberon/releases/download/v2024-01-18/uberon.owl

The following ontologies will not be updated in 4.1.0:

| Ontology | OBO Prefix | Release | Download |
|:--|:--|:--|:--|
| [Human Ancestry Ontology] | HANCESTRO | [3.0] | [hancestro-base.owl] |
| [Human Developmental Stages] |  HsapDv | 2020-03-10 | [hsapdv.owl] |
| [Mouse Developmental Stages]| MmusDv | 2020-03-10 | [mmusdv.owl] |
| [NCBI organismal classification] |  NCBITaxon | [2023-06-20] | [ncbitaxon.owl] |
| [Phenotype And Trait Ontology] | PATO | [2023-05-18] | [pato.owl]  |
| | | | |

GENCODE version bumps:
- v38 to v44 for humans
- M27 to M33 for mouse

**Comment by joyceyan** [comment]
We've merged in the new ontology files, but I'm opening this ticket back up because the dry run is producing this error:
```
ERROR:root:Error processing public dataset b2dda353-0c96-42df-8dcd-1ea7429a6feb, in collection 1b014f39-f202-45ae-bb7d-9286bddd8d8b: "No columns with matching prefix:'name_' found in var_df"
```

I pulled down the h5ad for this dataset and these are the columns in the var dataframe:
```
['name', 'ensg_id', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length']
```

I think the CXG conversion is supposed to add in a `name_` column for each dataset during upload, but that appears to not be working as expected.

One more thing I found is that this collection is on this ticket: https://github.com/chanzuckerberg/single-cell-data-portal/issues/4308 I don't think that the issue with curator name is related to this issue we're having with missing `name_` columns, but it could indicate some weird things happened on this collection.

**Comment by joyceyan** [comment]
Closing this out since we've updated all pinned ontologies + gencode versions. There were a few issues discovered as part of this migration:
1. The gencode dry run script is making some incorrect assumptions about how CXG conversion works (tracked [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/656))
2. We discovered some unexpected changes to gene lengths in the version upgrades. Pablo and the other comp bios are going to explore potentially changing how we calculate gene length to be a more stable calculation. If we roll that into schema 5.0, it'll be tracked as a separate ticket.
